name: bikeshare_streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - appnope
  - asttokens
  - backcall
  - blas
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - debugpy
  - decorator
  - entrypoints
  - executing
  - geographiclib
  - geopy
  - idna
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - libffi
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pyparsing
  - pysocks
  - python-dateutil
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
  - pip:
      - altair==5.3.0
      - attrs==23.2.0
      - blinker==1.8.2
      - branca==0.7.2
      - cachetools==5.3.3
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - fiona==1.9.6
      - folium==0.16.0
      - fonttools==4.51.0
      - geopandas==0.13.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mouseinfo==0.1.3
      - numpy==1.24.4
      - pandas==2.0.3
      - pillow==9.2.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pyautogui==0.9.53
      - pydeck==0.9.1
      - pygetwindow==0.0.9
      - pygments==2.18.0
      - pymsgbox==1.0.9
      - pyproj==3.5.0
      - pyrect==0.2.0
      - pyscreeze==0.1.28
      - pytweening==1.0.4
      - pytz==2024.1
      - referencing==0.35.1
      - requests==2.32.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - shapely==2.0.4
      - smmap==5.0.1
      - streamlit==1.34.0
      - streamlit-folium==0.22.1
      - tenacity==8.3.0
      - toml==0.10.2
      - toolz==0.12.1
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - watchdog==4.0.0
      - xyzservices==2024.4.0
      - zipp==3.18.2